### ISSUE TITLE
Cumbersome to use within virtual environments

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-watcher-vim#7]
When running vim within a virtual environment (that does not have aw-client installed) things go crazy. 

Also, sometimes you might use a non-system version of Python that use a different default pickle protocol (I got a warning when I installed aw-client in the virtualenv) which may have weird side effects.

**Comment by pascalwhoop** [comment]
Hi @ErikBjare ,
I just ran into this as well.
Maybe we can take some inspiration from here: https://github.com/python-mode/python-mode
They reference all required packages in their submodules folder and on my filesystem, these then render as complete projects --> some mechanism that resolves them locally so that they are "bundled" in a way. We could do the same here for `aw-core` and `aw-client`. 

Then just be aware that the vim plugin requires updates if the aw-core gets updated, otherwise vim will work with an old version. But I believe a vim plugin is not intended to depend on packages being installed in an external pip system, so that's the way to go. 

FYI, still working on that IDEA Plugin. Getting close to an alpha :-)

**Comment by ErikBjare** [comment]
@johan-bjareholt @ahnlabb This is getting really difficult for me, any chance you could fix it?

@pascalwhoop I described essentially that in https://github.com/ActivityWatch/aw-watcher-vim/issues/12, thanks for the tip!

**Comment by johan-bjareholt** [comment]
As long as aw-client depends on aw-core which has way too many dependencies @pascalwhoop solution won't be pretty.

aw-client only uses aw-core.config, aw-core.models and aw-core.dirs which are pretty minimal so if we were able to only install those it would be a step in the right direction.

For me personally though I'm much more annoyed by #13 

aw-watcher-vim really isn't stable yet, we probably shouldn't state that it is in the docs.
